### ISSUE TITLE
Load more page is not working

### ISSUE THREAD

**Issue by derrenx** [motebaya/Picuki#4]
can you fix the code ? i'am not expert in coding, but i know next page link has moved to
`<input class="pagination-next-page-input" type="hidden" value="`

After making request to `<div class="load-more-wrapper" data-next="/app/controllers/ajax.php?type=profile&end_cursor=QVFBcU1oSHJSY2U0WElXSWpjOUx4WUxac2RCTWh1TlRpdS1vMUFaU2NxRTNZSmVWYVRVckhWdG92OVFqckFIUEZiNnljNFN2M2dQVUN1cjlOTDBieE9PMQ==&end_cursor_mobile=3161282768902553987_3217616838&id=3217616838&ads=1">` the next page link will be in the page of ajax.php not in homepage

thanks a lot.

**Comment by motebaya** [comment]
> 

how did you know the next page has moved ?
![Screenshot from 2023-08-11 17-59-46](https://github.com/motebaya/Picuki/assets/106154800/b0a0754c-d4d0-4d7e-a4f2-03934d2ba77c)

here's no issue and nothing to fix, if still working as well. 
if you see error/exception , just show it.

**Comment by motebaya** [comment]
> can you fix the code ? i'am not expert in coding, but i know next page link has moved to `<input class="pagination-next-page-input" type="hidden" value="`
> 
> After making request to `<div class="load-more-wrapper" data-next="/app/controllers/ajax.php?type=profile&end_cursor=QVFBcU1oSHJSY2U0WElXSWpjOUx4WUxac2RCTWh1TlRpdS1vMUFaU2NxRTNZSmVWYVRVckhWdG92OVFqckFIUEZiNnljNFN2M2dQVUN1cjlOTDBieE9PMQ==&end_cursor_mobile=3161282768902553987_3217616838&id=3217616838&ads=1">` the next page link will be in the page of ajax.php not in homepage
> 
> thanks a lot.


how did you know the next page has moved ?
![Screenshot from 2023-08-11 17-59-46](https://github.com/motebaya/Picuki/assets/106154800/b0a0754c-d4d0-4d7e-a4f2-03934d2ba77c)

here's no issue and nothing to fix, if still working as well. 
if you see error/exception , just show it.

**Comment by derrenx** [comment]
only able to download 24 videos which is 2 page,because after first next page,next url will be change.
for example,from this `/app/controllers/ajax.php?type=profile&end_cursor=QVFBcU1oSHJSY2U0WElXSWpjOUx4WUxac2RCTWh1TlRpdS1vMUFaU2NxRTNZSmVWYVRVckhWdG92OVFqckFIUEZiNnljNFN2M2dQVUN1cjlOTDBieE9PMQ==&end_cursor_mobile=3161282768902553987_3217616838&id=3217616838&ads=1`
to this
`</div></li><input class="pagination-next-page-input" type="hidden" value="/app/controllers/ajax.php?type=profile&end_cursor_mobile=(random_numeric)&end_cursor=(random_numeric)&id=3217616838&ads=1&page_load_more=2"/>`

i've trying using "for each"  but get same media_id because nextpage is not working

sorry for my english,i'am still learning. thanks for your help.

**Comment by byteshiva** [comment]
Failed to download more images, its failing out.
```
 11:17:46 info:getting content from: 3223855416727133625 [8 of 24] 
Traceback (most recent call last):
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/streams/tls.py", line 133, in _call_sslobject_method
    result = func(*args)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/streams/tls.py", line 198, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1103, in receive
    await self._protocol.read_event.wait()
  File "/anaconda3/envs/instagrambulk/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7ff01f8e9ea0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "/anaconda3/envs/instagrambulk/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
    raise exc
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/connection.py", line 96, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 121, in handle_async_request
    raise exc
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 99, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 164, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 200, in _receive_event
    data = await self._network_stream.read(
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/anaconda3/envs/instagrambulk/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mywork/Picuki/main.py", line 280, in <module>
    asyncio.run(_main(
  File "/anaconda3/envs/instagrambulk/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/mywork/Picuki/main.py", line 207, in _main
    if (content := await module.get_media_content(media)):
  File "/mywork/Picuki/lib/Picuki.py", line 117, in get_media_content
    page = await self.get("/media/{}".format(
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/anaconda3/envs/instagrambulk/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
```

**Comment by motebaya** [comment]
> Failed to download more images, its failing out.
> 
> ```
>  11:17:46 info:getting content from: 3223855416727133625 [8 of 24] 
> Traceback (most recent call last):
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/streams/tls.py", line 133, in _call_sslobject_method
>     result = func(*args)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/ssl.py", line 917, in read
>     v = self._sslobj.read(len)
> ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
>     yield cancel_scope
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 34, in read
>     return await self._stream.receive(max_bytes=max_bytes)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/streams/tls.py", line 198, in receive
>     data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
>     data = await self.transport_stream.receive()
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1103, in receive
>     await self._protocol.read_event.wait()
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/asyncio/locks.py", line 214, in wait
>     await fut
> asyncio.exceptions.CancelledError: Cancelled by cancel scope 7ff01f8e9ea0
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
>     yield
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 32, in read
>     with anyio.fail_after(timeout):
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
>     raise TimeoutError
> TimeoutError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
>     yield
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
>     resp = await self._pool.handle_async_request(req)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
>     raise exc
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
>     response = await connection.handle_async_request(request)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/connection.py", line 96, in handle_async_request
>     return await self._connection.handle_async_request(request)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 121, in handle_async_request
>     raise exc
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 99, in handle_async_request
>     ) = await self._receive_response_headers(**kwargs)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 164, in _receive_response_headers
>     event = await self._receive_event(timeout=timeout)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_async/http11.py", line 200, in _receive_event
>     data = await self._network_stream.read(
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 31, in read
>     with map_exceptions(exc_map):
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ReadTimeout
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/mywork/Picuki/main.py", line 280, in <module>
>     asyncio.run(_main(
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/mywork/Picuki/main.py", line 207, in _main
>     if (content := await module.get_media_content(media)):
>   File "/mywork/Picuki/lib/Picuki.py", line 117, in get_media_content
>     page = await self.get("/media/{}".format(
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
>     return await self.request(
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
>     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
>     response = await self._send_handling_auth(
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
>     response = await self._send_handling_redirects(
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
>     response = await self._send_single_request(request)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
>     response = await transport.handle_async_request(request)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
>     with map_httpcore_exceptions():
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/anaconda3/envs/instagrambulk/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> ```

i think same right here https://github.com/motebaya/Picuki/issues/1 .

**Comment by taraglo** [comment]
The script only downloads 24 media IDs. There is no error because when it runs line 101 in `lib/Picuki.py`, beautifulsoup can't find the div with class `load-more-wrapper`. I am assuming it's because the website is using JavaScript to render images as the page scrolls down, so `httpx` doesn't wait long enough (or maybe at all) to get the new HTML content. As a result, `next_page` becomes `None` and the loop stops. 

After some failed attempt at fixing it, I just created a new `for-loop` logic in `main.py` that goes to each individual `/app/controllers/ajax.php` URLs directly and parses HTML to list all media IDs. The `end_cursor` value is set based on the last image received from `ajax.php` URL and then update all other params. Keep repeating until the api returns 500 error, meaning there are no images left.

Here's a short example of what I'm talking about:

```
# ... bunch of variable declarations

BASE_URL = "https://www.picuki.com/app/controllers/ajax.php?type=profile"

all_media_ids = []
has_more: bool = True

while has_more:
    r = httpx.get(BASE_URL, params={    
        "end_cursor_mobile": end_cursor_mobile,
        "end_cursor": end_cursor,
        "id": id,
        "ads": ads,
        "page_load_more": page_load_more
    }, cookies=cookies_api, headers=headers, timeout=timeout)

    if r.status_code == 500:
        has_more = False
        break

    soup = BeautifulSoup(r.text, 'html.parser')
    media_files = soup.find_all('div', class_='photo')
    
    for media in media_files:
        media_id = media.find('a').attrs.get('href').split('/')[-1]
        all_media_ids.append(media_id)

for id in alll_media_ids:
    req_url = "https://www.picuki.com/media/" + str(id)
    # send request to each media URL, parse returned HTML, get media content, and download them

```

Not the best solution, but it does the job. Could've made it asynchronous and stuff, but don't really care at this point tbh. The problem with this solution, however, is that Cloudfare will get suspicious of so many requests and eventually block you from accessing the site.

**Comment by motebaya** [comment]
> The script only downloads 24 media IDs. There is no error because when it runs line 101 in `lib/Picuki.py`, beautifulsoup can't find the div with class `load-more-wrapper`. I am assuming it's because the website is using JavaScript to render images as the page scrolls down, so `httpx` doesn't wait long enough (or maybe at all) to get the new HTML content. As a result, `next_page` becomes `None` and the loop stops.
> 
> After some failed attempt at fixing it, I just created a new `for-loop` logic in `main.py` that goes to each individual `/app/controllers/ajax.php` URLs directly and parses HTML to list all media IDs. The `end_cursor` value is set based on the last image received from `ajax.php` URL and then update all other params. Keep repeating until the api returns 500 error, meaning there are no images left.
> 
> Here's a short example of what I'm talking about:
> 
> .............

hi, thanks for reporting. 
I didn't expect that this small project would be discovered by more people. and yes, you're right. after check, it could only grab 24 media id (2 page) bcs element type is different, so `bs4` couldn't find it.

i'm currently trying to fix it, and it's working. 
grabbing `155` media id in `1min 15 secs` with 3 second delay per request page without any issue. It might feel a bit long time, but it's necessary to avoid spamming requests.
![ss-picuki](https://github.com/motebaya/Picuki/assets/106154800/14420df8-6862-448b-a697-e80047a81071)

I will refactor it back ASAP. Thanks.

**Comment by motebaya** [comment]
fixed at: https://github.com/motebaya/Picuki/blob/66518b92b5de335c0d179726f122c086d3712b9c/lib/Picuki.py#L101
